/// Flutter icons OotmIconPack
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OotmIconPack
///      fonts:
///       - asset: fonts/OotmIconPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OotmIconPack {
  OotmIconPack._();

  static const _kFontFam = 'OotmIconPack';

  static const IconData arrow_back = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData arrow_swipe = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData favs_full = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData favs_outline = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData locked = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData menu_help_feedback = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData menu_onboarding = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData menu_privacy = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData navbar_home = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData navbar_info = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData navbar_schedule = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe80f, fontFamily: _kFontFam);
}
