/// Flutter icons OotmIconPack
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OotmIconPack
///      fonts:
///       - asset: fonts/OotmIconPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OotmIconPack {
  OotmIconPack._();

  static const _kFontFam = 'OotmIconPack';

  static const IconData close = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData favs_full = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData favs_outline = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData new_messages = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData sbar_account = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData sbar_button = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData sbar_help = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData sbar_helper = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData sbar_notifications = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData sbar_privacy = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData sbar_team = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData schedule = const IconData(0xe80d, fontFamily: _kFontFam);
}
